interface=eth2
listen-address=127.0.0.1,192.168.8.123
bind-interfaces
port=53
domain-needed
bogus-priv
no-resolv
cache-size=1000
log-queries
log-facility=/var/log/codex-dnsmasq.log
server=223.5.5.5
server=8.8.8.8

local=/dns.msftncsi.com/
address=/dns.msftncsi.com/131.107.255.255

local=/dss0.bdstatic.com/
address=/dss0.bdstatic.com/0.0.0.0
address=/dss0.bdstatic.com/::

local=/.mjhy2.com/
local=/mjhy2.com/
address=/.mjhy2.com/0.0.0.0
address=/mjhy2.com/0.0.0.0
address=/.mjhy2.com/::
address=/mjhy2.com/::

local=/fonts.googleapis.com/
address=/fonts.googleapis.com/0.0.0.0
address=/fonts.googleapis.com/::
