; CLIPS fact schema v1 for codex-lan-agent MCP guard integration.

(deftemplate mcp_tool_request
  (slot tool_name)
  (slot task_id (default ""))
  (slot provider_id (default ""))
  (slot capability_id (default ""))
  (slot build_dir (default ""))
  (slot project_root (default ""))
  (slot test_regex (default ""))
  (slot session_id (default ""))
  (slot turn_id (default ""))
  (slot reasoning_level (default ""))
  (slot primary_intent (default ""))
  (slot preflight_status (default "missing"))
  (slot dedup_status (default ""))
  (slot canonical_slice_id (default ""))
  (slot dup_of (default ""))
  (slot route_hint (default ""))
  (slot source_type (default ""))
  (slot file_path (default ""))
  (slot directory_path (default ""))
  (slot scan_mode (default ""))
  (slot probe_ref (default ""))
  (slot patch_id (default ""))
  (slot request_id (default ""))
  (slot trace_id (default ""))
  (slot old_hash (default ""))
  (slot probe_ready (default "false"))
  (slot preview_ready (default "false"))
  (slot revert_plan_ready (default "false"))
  (slot path_within_workspace (default "false"))
  (slot file_count (default "1"))
  (slot max_items_per_call (default ""))
  (slot single_step_required (default "false"))
  (slot operation_granularity (default ""))
  (slot batch_mutation_allowed (default "false"))
  (slot explicit_user_intent (default "false"))
  (slot probe_required (default "false"))
  (slot requires_preview (default "false"))
  (slot requires_approval (default "false"))
  (slot requires_revert_plan (default "false"))
  (slot requires_post_verify (default "false"))
  (slot pending_continuation_active (default "false"))
  (slot pending_required_tool (default ""))
  (slot pending_required_arguments_json (default ""))
  (slot pending_trace_id (default ""))
  (slot pending_goal_id (default ""))
  (slot pending_source_tool (default ""))
  (slot pending_hash (default ""))
  (slot pending_trace_match (default "false"))
  (slot continuation_takeover_allowed (default "true")))

(deftemplate mcp_tool_result
  (slot tool_name)
  (slot request_id (default ""))
  (slot trace_id (default ""))
  (slot tool_call_id (default ""))
  (slot provider_id (default ""))
  (slot capability_id (default ""))
  (slot task_id (default ""))
  (slot session_id (default ""))
  (slot turn_id (default ""))
  (slot direct_answer (default ""))
  (slot summary (default ""))
  (slot assistant_text (default ""))
  (slot error (default ""))
  (slot error_code (default ""))
  (slot error_message (default ""))
  (slot status (default ""))
  (slot tool_use_decision (default ""))
  (slot task_completion (default ""))
  (slot has_more (default "false"))
  (slot next_start_line (default ""))
  (slot next_call_json (default ""))
  (slot continue_required (default "false"))
  (slot auto_continue_required (default "false"))
  (slot analysis_allowed (default "true"))
  (slot batch_completion (default ""))
  (slot remaining_batch_file_count (default "0"))
  (slot next_batch_file_path (default ""))
  (slot known_file_list_complete (default ""))
  (slot directory_listing_complete (default ""))
  (slot directory_scope_active (default "false"))
  (slot directory_manifest_path (default ""))
  (slot directory_current_file_index (default "0"))
  (slot directory_next_file_index (default ""))
  (slot directory_total_code_file_count (default "0"))
  (slot directory_remaining_code_file_count (default "0"))
  (slot directory_scope_incomplete (default "false"))
  (slot directory_next_probe_call_json (default ""))
  (slot flow_id (default ""))
  (slot flow_task_list_required (default "false"))
  (slot flow_current_task_id (default ""))
  (slot flow_next_task_id (default ""))
  (slot flow_task_list_path (default ""))
  (slot flow_task_list_md_path (default ""))
  (slot content_read_completion (default ""))
  (slot incomplete_scope (default ""))
  (slot terminal_state (default ""))
  (slot completion_claim_allowed (default ""))
  (slot final_answer_allowed (default ""))
  (slot result_hash (default ""))
  (slot schema_version (default ""))
  (slot result_schema_id (default ""))
  (slot ai_conclusion_valid (default "true"))
  (slot result_ref (default ""))
  (slot evidence_ref (default ""))
  (slot log_path (default ""))
  (slot patch_id (default ""))
  (slot write_verified (default ""))
  (slot disk_write_completed (default ""))
  (slot single_step_required (default ""))
  (slot operation_granularity (default ""))
  (slot max_items_per_call (default ""))
  (slot batch_mutation_allowed (default ""))
  (slot step_completion (default ""))
  (slot step_contract (default "")))

(deftemplate mcp_tool_chain
  (slot chain_template_id (default "mcp_tool_chain_v1"))
  (slot tool_name)
  (slot chain_phase (default "pre_call"))
  (slot request_type (default "generic_mcp_tool"))
  (slot risk (default "medium"))
  (slot safety_class (default "controlled"))
  (slot execution_class (default "unknown"))
  (slot evidence_policy (default "standard_result_envelope"))
  (slot clips_required (default "true"))
  (slot rule_namespace (default "mcp_tool_guard"))
  (slot result_ref (default ""))
  (slot evidence_ref (default ""))
  (slot task_id (default ""))
  (slot analysis_only (default "false"))
  (slot execution_capability (default "")))

(deftemplate slice_ingest_fact
  (slot task_id (default ""))
  (slot session_id (default ""))
  (slot turn_id (default ""))
  (slot provider_id (default ""))
  (slot capability_id (default ""))
  (slot business_user_text (default ""))
  (slot business_assistant_text (default ""))
  (slot business_summary (default ""))
  (slot dedup_hash (default ""))
  (slot canonical_slice_id (default ""))
  (slot dup_of (default ""))
  (slot dedup_status (default ""))
  (slot source_type (default "")))

(deftemplate cxparser_fact
  (slot tool_name)
  (slot parse_status (default "missing"))
  (slot symbol_status (default "missing"))
  (slot target_status (default "missing"))
  (slot error_status (default "missing"))
  (slot preflight_status (default "missing")))

(deftemplate clips_decision
  (slot domain)
  (slot target (default "tool"))
  (slot decision (default "allow"))
  (slot verification (default "verified"))
  (slot next_action (default ""))
  (slot reason_code (default ""))
  (slot matched_rule (default ""))
  (slot route_target (default ""))
  (slot route_arguments_json (default "")))

(deftemplate mcp_flow_observation
  (slot flow_id (default ""))
  (slot phase (default ""))
  (slot tool_name (default ""))
  (slot status (default ""))
  (slot expected_next_tool (default ""))
  (slot terminal_allowed (default "false"))
  (slot completion_allowed (default "false"))
  (slot reason_code (default ""))
  (slot matched_rule (default ""))
  (slot evidence_ref (default "")))

(deftemplate mcp_flow_expectation
  (slot flow_id (default ""))
  (slot current_tool (default ""))
  (slot expected_next_tool (default ""))
  (slot continuation_required (default "false"))
  (slot manual_content_processing_allowed (default "false"))
  (slot completion_gate (default "terminal_state=true + completion_claim_allowed=true + final_answer_allowed=true + verification_ok=true"))
  (slot reason_code (default "")))
