#!/usr/bin/env python3
"""
Build a local semantic monitor dashboard from semantic_monitor artifacts.

Inputs:
  semantic_monitor/ with markdown/json/dot files generated by MCP analysis.

Outputs:
  semantic_monitor_dashboard_sqlite/
    semantic_monitor.db
    semantic_monitor.sql
    objects/
    object_manifest.json
    dashboard/index.html
    dashboard/dashboard_data.js

The dashboard is intentionally static and dependency-free. SQLite stores the
queryable review index; copied file objects preserve source evidence.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


TEXT_EXTENSIONS = {".md", ".txt", ".dot"}
JSON_EXTENSIONS = {".json"}


def now_iso() -> str:
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig", errors="replace")


def read_json(path: Path) -> Any:
    try:
        return json.loads(read_text(path))
    except Exception:
        return None


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_text(text: str) -> str:
    return sha256_bytes(text.encode("utf-8", errors="replace"))


def slugify(value: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9_.-]+", "_", value).strip("_")
    return slug or "item"


def first_non_empty(*values: Any) -> str:
    for value in values:
        if value is None:
            continue
        text = str(value).strip()
        if text:
            return text
    return ""


def normalize_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True)


def classify_document(rel_path: str) -> str:
    path = rel_path.replace("\\", "/").lower()
    if path.startswith("trace_cards/"):
        return "trace_card"
    if path.startswith("lenses/"):
        return "lens"
    if path.startswith("increment/"):
        return "increment"
    if "risk_queue" in path:
        return "risk_queue"
    if "gap_queue" in path:
        return "gap_queue"
    if "issues" in path:
        return "issues"
    if path.endswith(".json"):
        return "json"
    if path.endswith(".dot"):
        return "graph_dot"
    if path.endswith(".md"):
        return "markdown"
    return "object"


def markdown_title(text: str, fallback: str) -> str:
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            return stripped.lstrip("#").strip() or fallback
    return fallback


def infer_judgment(text: str) -> str:
    lower = text.lower()
    if "partial" in lower or "⚠" in text:
        return "partial"
    if "aligned" in lower or "✅" in text:
        return "aligned"
    if "missing" in lower:
        return "missing"
    if "suspicious" in lower:
        return "suspicious"
    return "unknown"


def infer_risk_level(text: str) -> str:
    lower = text.lower()
    if "critical" in lower or "严重" in lower:
        return "critical"
    if "high" in lower or "高" in lower:
        return "high"
    if "medium" in lower or "partial" in lower or "中" in lower:
        return "medium"
    if "low" in lower or "低" in lower:
        return "low"
    return "unknown"


def extract_round_refs(text: str) -> Tuple[str, str]:
    lower = text.lower()
    introduced = ""
    touched = ""
    intro_match = re.search(r"round\s*([0-9]+)\s*(?:引入|introduced)?", lower)
    if intro_match:
        introduced = "round_" + intro_match.group(1)
    touched_matches = re.findall(r"round\s*([0-9]+)", lower)
    if touched_matches:
        touched = "round_" + touched_matches[-1]
    return introduced, touched


def connect_db(db_path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(str(db_path))
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


SCHEMA = """
CREATE TABLE IF NOT EXISTS documents (
  document_id TEXT PRIMARY KEY,
  rel_path TEXT NOT NULL,
  object_path TEXT NOT NULL,
  kind TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  sha256 TEXT NOT NULL,
  title TEXT,
  content TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS nodes (
  node_id TEXT PRIMARY KEY,
  layer TEXT,
  semantic_name TEXT,
  parent_id TEXT,
  child_count INTEGER DEFAULT 0,
  evidence_type TEXT,
  risk_level TEXT,
  round_id TEXT,
  source_document_id TEXT,
  raw_json TEXT
);

CREATE TABLE IF NOT EXISTS edges (
  edge_id TEXT PRIMARY KEY,
  source_node_id TEXT,
  target_node_id TEXT,
  relation_type TEXT,
  raw_json TEXT
);

CREATE TABLE IF NOT EXISTS artifacts (
  artifact_id TEXT PRIMARY KEY,
  artifact_path TEXT,
  artifact_type TEXT,
  source_file TEXT,
  status TEXT,
  node_count INTEGER,
  edge_count INTEGER,
  fragment_count INTEGER,
  description TEXT,
  raw_json TEXT
);

CREATE TABLE IF NOT EXISTS rounds (
  round_id TEXT PRIMARY KEY,
  round_index INTEGER,
  round_type TEXT,
  input_source TEXT,
  base_artifact TEXT,
  output_summary TEXT,
  added_fragment_count INTEGER,
  skipped_duplicate_fragment_count INTEGER,
  delta_fragment_count INTEGER,
  delta_node_count INTEGER,
  risk_count INTEGER,
  human_review_status TEXT DEFAULT 'pending',
  raw_json TEXT
);

CREATE TABLE IF NOT EXISTS trace_cards (
  card_id TEXT PRIMARY KEY,
  document_id TEXT NOT NULL,
  title TEXT,
  judgment TEXT,
  risk_level TEXT,
  introduced_round TEXT,
  last_touched_round TEXT,
  human_review_status TEXT DEFAULT 'pending',
  content TEXT
);

CREATE TABLE IF NOT EXISTS issues (
  issue_id TEXT PRIMARY KEY,
  document_id TEXT,
  title TEXT,
  severity TEXT,
  status TEXT,
  content TEXT
);

CREATE TABLE IF NOT EXISTS lenses (
  lens_id TEXT PRIMARY KEY,
  document_id TEXT NOT NULL,
  title TEXT,
  lens_type TEXT,
  content TEXT
);

CREATE TABLE IF NOT EXISTS review_decisions (
  review_id TEXT PRIMARY KEY,
  target_type TEXT NOT NULL,
  target_id TEXT NOT NULL,
  decision TEXT NOT NULL,
  notes TEXT,
  reviewer TEXT,
  updated_at TEXT NOT NULL
);
"""


def reset_output(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for child in ["dashboard", "objects"]:
        path = output_dir / child
        if path.exists():
            shutil.rmtree(path)
        path.mkdir(parents=True, exist_ok=True)
    for filename in ["semantic_monitor.db", "semantic_monitor.sql", "object_manifest.json", "dashboard_data.json"]:
        path = output_dir / filename
        if path.exists():
            path.unlink()


def copy_objects(input_dir: Path, output_dir: Path) -> List[Dict[str, Any]]:
    objects_dir = output_dir / "objects"
    manifest: List[Dict[str, Any]] = []
    for path in sorted(input_dir.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(input_dir).as_posix()
        data = path.read_bytes()
        digest = sha256_bytes(data)
        object_name = f"{digest[:16]}_{slugify(rel)}"
        object_path = objects_dir / object_name
        object_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, object_path)
        manifest.append({
            "document_id": digest[:16],
            "rel_path": rel,
            "object_path": object_path.relative_to(output_dir).as_posix(),
            "kind": classify_document(rel),
            "size_bytes": len(data),
            "sha256": digest,
            "title": path.stem,
        })
    (output_dir / "object_manifest.json").write_text(
        json.dumps({"objects": manifest}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return manifest


def insert_documents(conn: sqlite3.Connection, input_dir: Path, output_dir: Path, manifest: List[Dict[str, Any]]) -> Dict[str, str]:
    rel_to_doc: Dict[str, str] = {}
    for item in manifest:
        rel = item["rel_path"]
        path = input_dir / rel
        content = ""
        title = item["title"]
        if path.suffix.lower() in TEXT_EXTENSIONS or path.suffix.lower() in JSON_EXTENSIONS:
            content = read_text(path)
            if path.suffix.lower() == ".md":
                title = markdown_title(content, path.stem)
        conn.execute(
            """
            INSERT INTO documents(document_id, rel_path, object_path, kind, size_bytes, sha256, title, content, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                item["document_id"],
                rel,
                item["object_path"],
                item["kind"],
                item["size_bytes"],
                item["sha256"],
                title,
                content,
                now_iso(),
            ),
        )
        rel_to_doc[rel] = item["document_id"]
    return rel_to_doc


def load_semantic_network(input_dir: Path) -> Dict[str, Any]:
    data = read_json(input_dir / "semantic_network.json")
    return data if isinstance(data, dict) else {}


def load_navigation_tree(input_dir: Path) -> Dict[str, Any]:
    data = read_json(input_dir / "navigation_tree.json")
    return data if isinstance(data, dict) else {}


def insert_nodes_and_edges(conn: sqlite3.Connection, input_dir: Path, rel_to_doc: Dict[str, str]) -> None:
    semantic = load_semantic_network(input_dir)
    navigation = load_navigation_tree(input_dir)
    source_doc = rel_to_doc.get("semantic_network.json", "")

    nodes: Dict[str, Dict[str, Any]] = {}
    for node in semantic.get("key_nodes", []) or []:
        node_id = node.get("node_id")
        if node_id:
            nodes[node_id] = dict(node)
    nav_root = navigation.get("navigation_tree", {})
    for node in nav_root.get("high_value_nodes", []) or []:
        node_id = node.get("node_id")
        if node_id:
            merged = nodes.get(node_id, {})
            merged.update(node)
            nodes[node_id] = merged

    layer_dist = nav_root.get("layer_distribution", {})
    for layer, info in layer_dist.items():
        if isinstance(info, dict) and info.get("node_id"):
            node_id = str(info.get("node_id"))
            nodes.setdefault(node_id, {
                "node_id": node_id,
                "layer": layer,
                "semantic_name": first_non_empty(info.get("summary"), layer),
                "child_count": info.get("children_count", info.get("count", 0)),
            })
        if isinstance(info, dict) and isinstance(info.get("children"), dict):
            for key, child in info["children"].items():
                node_id = child.get("node_id")
                if node_id:
                    nodes.setdefault(node_id, {
                        "node_id": node_id,
                        "layer": layer,
                        "semantic_name": key,
                        "parent_id": info.get("parent"),
                        "child_count": child.get("children_count", 0),
                        "raw_json": child,
                    })

    for node_id, node in sorted(nodes.items()):
        conn.execute(
            """
            INSERT OR REPLACE INTO nodes(node_id, layer, semantic_name, parent_id, child_count, evidence_type, risk_level, round_id, source_document_id, raw_json)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                node_id,
                first_non_empty(node.get("layer"), infer_layer(node_id)),
                first_non_empty(node.get("semantic_name"), node.get("summary"), node_id),
                node.get("parent_id") or node.get("parent"),
                int_or_zero(node.get("child_count", node.get("children_count", 0))),
                node.get("evidence_type") or node.get("evidence_strength"),
                infer_risk_level(normalize_json(node)),
                infer_round_from_node(node_id),
                source_doc,
                normalize_json(node),
            ),
        )

    edge_types = (semantic.get("edges_summary", {}) or {}).get("types", {}) or {}
    edge_index = 0
    for relation, count in edge_types.items():
        edge_index += 1
        conn.execute(
            "INSERT OR REPLACE INTO edges(edge_id, relation_type, raw_json) VALUES (?, ?, ?)",
            (f"summary_edge_{edge_index}", relation, normalize_json({"count": count})),
        )


def infer_layer(node_id: str) -> str:
    for layer in ["L1_META", "L2_DOMAIN", "L3_FLOW", "L4_ATOM", "L5_RAW"]:
        if node_id.startswith(layer):
            return layer
    return ""


def infer_round_from_node(node_id: str) -> str:
    match = re.search(r"frag_([0-9]+)", node_id)
    if not match:
        return ""
    number = int(match.group(1))
    if number <= 1021:
        return "round_1"
    if number <= 1023:
        return "round_2"
    if number <= 1025:
        return "round_3"
    return "round_4"


def int_or_zero(value: Any) -> int:
    try:
        return int(value)
    except Exception:
        return 0


def insert_artifacts(conn: sqlite3.Connection, input_dir: Path) -> None:
    artifacts = read_json(input_dir / "artifacts_index.json")
    if not isinstance(artifacts, dict):
        return
    for artifact_id, item in sorted(artifacts.items()):
        if not isinstance(item, dict):
            continue
        conn.execute(
            """
            INSERT OR REPLACE INTO artifacts(artifact_id, artifact_path, artifact_type, source_file, status, node_count, edge_count, fragment_count, description, raw_json)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                artifact_id,
                item.get("path"),
                item.get("type"),
                item.get("source_file"),
                item.get("status"),
                int_or_zero(item.get("node_count")),
                int_or_zero(item.get("edge_count")),
                int_or_zero(item.get("fragments", item.get("fragment_count"))),
                item.get("description"),
                normalize_json(item),
            ),
        )


def insert_rounds(conn: sqlite3.Connection, input_dir: Path) -> None:
    ledger = read_json(input_dir / "increment" / "increment_ledger.json")
    if not isinstance(ledger, dict):
        return
    root = ledger.get("increment_ledger", ledger)
    for item in root.get("rounds", []) or []:
        if not isinstance(item, dict):
            continue
        round_index = int_or_zero(item.get("round_id", item.get("round_index")))
        round_id = f"round_{round_index}" if round_index else slugify(str(item.get("round_type", "round")))
        delta_nodes = item.get("delta_nodes") or {}
        total_delta_nodes = int_or_zero(delta_nodes.get("total_added")) if isinstance(delta_nodes, dict) else 0
        conn.execute(
            """
            INSERT OR REPLACE INTO rounds(round_id, round_index, round_type, input_source, base_artifact, output_summary,
              added_fragment_count, skipped_duplicate_fragment_count, delta_fragment_count, delta_node_count, risk_count, raw_json)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                round_id,
                round_index,
                item.get("round_type"),
                normalize_json(item.get("input_source", {})),
                item.get("base_artifact"),
                item.get("output_summary"),
                int_or_zero(item.get("added_fragment_count")),
                int_or_zero(item.get("skipped_duplicate_fragment_count")),
                int_or_zero(item.get("delta_fragments", item.get("added_fragment_count"))),
                total_delta_nodes,
                int_or_zero(item.get("risk_count")),
                normalize_json(item),
            ),
        )


def insert_markdown_derived(conn: sqlite3.Connection, input_dir: Path, rel_to_doc: Dict[str, str]) -> None:
    for rel, doc_id in rel_to_doc.items():
        path = input_dir / rel
        if path.suffix.lower() != ".md":
            continue
        content = read_text(path)
        title = markdown_title(content, Path(rel).stem)
        normalized = rel.replace("\\", "/")
        if normalized.startswith("trace_cards/"):
            card_id = Path(rel).stem
            introduced, touched = extract_round_refs(content)
            conn.execute(
                """
                INSERT OR REPLACE INTO trace_cards(card_id, document_id, title, judgment, risk_level, introduced_round, last_touched_round, content)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (card_id, doc_id, title, infer_judgment(content), infer_risk_level(content), introduced, touched, content),
            )
        elif normalized.startswith("lenses/"):
            lens_id = Path(rel).stem
            conn.execute(
                """
                INSERT OR REPLACE INTO lenses(lens_id, document_id, title, lens_type, content)
                VALUES (?, ?, ?, ?, ?)
                """,
                (lens_id, doc_id, title, lens_id.replace("_lens", ""), content),
            )
        elif normalized in {"issues.md", "risk_queue.md", "gap_queue.md"}:
            issue_id = Path(rel).stem
            conn.execute(
                """
                INSERT OR REPLACE INTO issues(issue_id, document_id, title, severity, status, content)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                (issue_id, doc_id, title, infer_risk_level(content), "open", content),
            )


def export_sql(conn: sqlite3.Connection, output_path: Path) -> None:
    output_path.write_text("\n".join(conn.iterdump()), encoding="utf-8")


def query_all(conn: sqlite3.Connection, sql: str) -> List[Dict[str, Any]]:
    conn.row_factory = sqlite3.Row
    rows = conn.execute(sql).fetchall()
    return [dict(row) for row in rows]


def build_dashboard_data(conn: sqlite3.Connection, input_dir: Path) -> Dict[str, Any]:
    semantic = load_semantic_network(input_dir)
    navigation = load_navigation_tree(input_dir)
    return {
        "generated_at": now_iso(),
        "summary": {
            "total_nodes": int_or_zero((semantic.get("nodes_summary", {}) or {}).get("total")),
            "total_edges": int_or_zero((semantic.get("edges_summary", {}) or {}).get("total")),
            "layers": semantic.get("layers", {}),
            "latest_artifact": ((read_json(input_dir / "increment" / "increment_ledger.json") or {}).get("increment_ledger", {}) or {}).get("latest_artifact", ""),
        },
        "navigation": navigation.get("navigation_tree", navigation),
        "nodes": query_all(conn, "SELECT * FROM nodes ORDER BY layer, node_id LIMIT 5000"),
        "rounds": query_all(conn, "SELECT * FROM rounds ORDER BY round_index"),
        "artifacts": query_all(conn, "SELECT * FROM artifacts ORDER BY artifact_id"),
        "trace_cards": query_all(conn, "SELECT * FROM trace_cards ORDER BY judgment, card_id"),
        "issues": query_all(conn, "SELECT * FROM issues ORDER BY severity DESC, issue_id"),
        "lenses": query_all(conn, "SELECT lens_id, title, lens_type, content FROM lenses ORDER BY lens_id"),
        "documents": query_all(conn, "SELECT document_id, rel_path, object_path, kind, size_bytes, title FROM documents ORDER BY kind, rel_path"),
    }


HTML = r"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Semantic Monitor Dashboard</title>
  <style>
    :root { color-scheme: light; --bg:#f6f7f9; --panel:#fff; --ink:#18202a; --muted:#647184; --line:#dce1e8; --accent:#1f6feb; --risk:#b42318; --ok:#1a7f37; --warn:#9a6700; }
    * { box-sizing: border-box; }
    body { margin:0; font:14px/1.45 "Segoe UI", Arial, sans-serif; color:var(--ink); background:var(--bg); }
    header { height:64px; display:flex; align-items:center; gap:18px; padding:0 22px; border-bottom:1px solid var(--line); background:#fff; position:sticky; top:0; z-index:2; }
    h1 { font-size:18px; margin:0; }
    .summary { display:flex; gap:10px; flex-wrap:wrap; color:var(--muted); }
    .pill { border:1px solid var(--line); background:#f8fafc; border-radius:999px; padding:4px 9px; white-space:nowrap; }
    main { display:grid; grid-template-columns:260px minmax(420px,1fr) 360px; min-height:calc(100vh - 64px); }
    nav, aside { border-right:1px solid var(--line); background:#fff; padding:16px; overflow:auto; }
    aside { border-right:0; border-left:1px solid var(--line); }
    section { padding:18px; overflow:auto; }
    button { width:100%; text-align:left; border:1px solid var(--line); background:#fff; border-radius:8px; padding:9px 10px; margin:4px 0; color:var(--ink); cursor:pointer; }
    button.active, button:hover { border-color:var(--accent); background:#eef5ff; }
    input, select, textarea { width:100%; border:1px solid var(--line); border-radius:8px; padding:9px 10px; font:inherit; background:#fff; }
    textarea { min-height:90px; resize:vertical; }
    .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(180px,1fr)); gap:12px; }
    .card { border:1px solid var(--line); background:var(--panel); border-radius:10px; padding:14px; margin-bottom:12px; }
    .card h3 { margin:0 0 8px; font-size:15px; }
    .muted { color:var(--muted); }
    .mono { font-family:Consolas, "SFMono-Regular", monospace; font-size:12px; word-break:break-all; }
    .list { display:grid; gap:8px; }
    .row { border:1px solid var(--line); border-radius:8px; background:#fff; padding:10px; cursor:pointer; }
    .row:hover { border-color:var(--accent); }
    .tag { display:inline-block; border:1px solid var(--line); border-radius:6px; padding:2px 6px; margin:2px; font-size:12px; color:var(--muted); }
    .risk-high,.risk-critical { color:var(--risk); font-weight:600; }
    .risk-medium,.partial { color:var(--warn); font-weight:600; }
    .aligned,.ok { color:var(--ok); font-weight:600; }
    pre { white-space:pre-wrap; word-break:break-word; background:#f8fafc; border:1px solid var(--line); border-radius:8px; padding:12px; max-height:460px; overflow:auto; }
    .split { display:grid; grid-template-columns:1fr 1fr; gap:12px; }
    @media (max-width: 1100px) { main { grid-template-columns:1fr; } nav, aside { border:0; border-bottom:1px solid var(--line); } }
  </style>
</head>
<body>
  <header>
    <h1>Semantic Monitor Dashboard</h1>
    <div id="headerSummary" class="summary"></div>
  </header>
  <main>
    <nav>
      <input id="search" placeholder="搜索 node / round / artifact / card" />
      <div style="height:10px"></div>
      <button data-view="overview" class="active">Overview</button>
      <button data-view="navigation">Layer Navigation</button>
      <button data-view="rounds">Increment Ledger</button>
      <button data-view="risks">Risks & Gaps</button>
      <button data-view="cards">Trace Cards</button>
      <button data-view="artifacts">Artifacts</button>
      <button data-view="lenses">Lenses</button>
      <button data-view="objects">Object Store</button>
    </nav>
    <section id="content"></section>
    <aside>
      <div class="card">
        <h3>Review Decision</h3>
        <div id="selectedTarget" class="muted">选择一个节点、卡片或 artifact</div>
        <div style="height:10px"></div>
        <select id="decision">
          <option value="pending">pending</option>
          <option value="accepted">accepted</option>
          <option value="rejected">rejected</option>
          <option value="needs_more_evidence">needs_more_evidence</option>
        </select>
        <div style="height:8px"></div>
        <textarea id="notes" placeholder="人工研判备注"></textarea>
        <div style="height:8px"></div>
        <button id="saveDecision">保存到本机浏览器</button>
      </div>
      <div class="card">
        <h3>Current Detail</h3>
        <pre id="detail">No selection</pre>
      </div>
    </aside>
  </main>
  <script src="dashboard_data.js"></script>
  <script>
    const data = window.SEMANTIC_DASHBOARD_DATA;
    let view = "overview";
    let selected = null;
    const $ = (id) => document.getElementById(id);
    const esc = (v) => String(v ?? "").replace(/[&<>]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[ch]));
    const text = (v) => typeof v === "string" ? v : JSON.stringify(v, null, 2);
    function setDetail(type, id, payload) {
      selected = {type, id, payload};
      $("selectedTarget").textContent = `${type}: ${id}`;
      $("detail").textContent = JSON.stringify(payload, null, 2);
      const saved = JSON.parse(localStorage.getItem("semanticReview:" + type + ":" + id) || "{}");
      $("decision").value = saved.decision || "pending";
      $("notes").value = saved.notes || "";
    }
    function filterItems(items, fields) {
      const q = $("search").value.trim().toLowerCase();
      if (!q) return items;
      return items.filter(item => fields.some(f => String(item[f] ?? "").toLowerCase().includes(q)) || JSON.stringify(item).toLowerCase().includes(q));
    }
    function row(label, sub, payload, type, id, extra="") {
      return `<div class="row" data-type="${esc(type)}" data-id="${esc(id)}"><b>${esc(label)}</b> ${extra}<div class="muted mono">${esc(sub)}</div></div>`;
    }
    function bindRows(itemsById) {
      document.querySelectorAll(".row[data-id]").forEach(el => {
        el.onclick = () => {
          const key = el.dataset.type + ":" + el.dataset.id;
          setDetail(el.dataset.type, el.dataset.id, itemsById[key] || {});
        };
      });
    }
    function renderOverview() {
      const s = data.summary || {};
      const layers = s.layers || {};
      $("content").innerHTML = `
        <div class="grid">
          <div class="card"><h3>Total Nodes</h3><div style="font-size:28px">${esc(s.total_nodes)}</div></div>
          <div class="card"><h3>Total Edges</h3><div style="font-size:28px">${esc(s.total_edges)}</div></div>
          <div class="card"><h3>Latest Artifact</h3><div class="mono">${esc(s.latest_artifact)}</div></div>
          <div class="card"><h3>Trace Cards</h3><div style="font-size:28px">${data.trace_cards.length}</div></div>
        </div>
        <div class="card"><h3>Layer Distribution</h3>${Object.entries(layers).map(([k,v])=>`<span class="tag">${esc(k)}: ${esc(v)}</span>`).join("")}</div>
        <div class="split">
          <div class="card"><h3>Risk Queue</h3>${data.issues.map(i=>`<div class="tag ${esc(i.severity)}">${esc(i.issue_id)} · ${esc(i.severity)}</div>`).join("")}</div>
          <div class="card"><h3>Increment Rounds</h3>${data.rounds.map(r=>`<div class="tag">${esc(r.round_id)} +${esc(r.added_fragment_count)} fragments</div>`).join("")}</div>
        </div>`;
    }
    function renderNavigation() {
      const nodes = filterItems(data.nodes, ["node_id","layer","semantic_name","round_id"]);
      const map = {};
      $("content").innerHTML = `<div class="card"><h3>Layer Navigation</h3><div class="list">${nodes.map(n => {
        map["node:"+n.node_id]=n;
        return row(n.node_id, `${n.layer || ""} · ${n.semantic_name || ""} · round=${n.round_id || ""}`, n, "node", n.node_id, `<span class="tag">${esc(n.child_count)} children</span>`);
      }).join("")}</div></div>`;
      bindRows(map);
    }
    function renderRounds() {
      const rounds = filterItems(data.rounds, ["round_id","round_type","input_source","output_summary"]);
      const map = {};
      $("content").innerHTML = `<div class="card"><h3>Increment Ledger</h3><div class="list">${rounds.map(r => {
        map["round:"+r.round_id]=r;
        return row(r.round_id, `${r.round_type || ""} · output=${r.output_summary || ""}`, r, "round", r.round_id, `<span class="tag">+${esc(r.added_fragment_count)} fragments</span><span class="tag">${esc(r.delta_node_count)} delta nodes</span>`);
      }).join("")}</div></div>`;
      bindRows(map);
    }
    function renderRisks() {
      const issues = filterItems(data.issues, ["issue_id","title","severity","content"]);
      const map = {};
      $("content").innerHTML = `<div class="card"><h3>Risks & Gaps</h3><div class="list">${issues.map(i => {
        map["issue:"+i.issue_id]=i;
        return row(i.title || i.issue_id, i.content?.slice(0, 180) || "", i, "issue", i.issue_id, `<span class="tag risk-${esc(i.severity)}">${esc(i.severity)}</span>`);
      }).join("")}</div></div>`;
      bindRows(map);
    }
    function renderCards() {
      const cards = filterItems(data.trace_cards, ["card_id","title","judgment","content"]);
      const map = {};
      $("content").innerHTML = `<div class="card"><h3>Trace Cards</h3><div class="list">${cards.map(c => {
        map["card:"+c.card_id]=c;
        return row(c.title || c.card_id, `${c.judgment || ""} · ${c.introduced_round || ""} -> ${c.last_touched_round || ""}`, c, "card", c.card_id, `<span class="tag ${esc(c.judgment)}">${esc(c.judgment)}</span>`);
      }).join("")}</div></div>`;
      bindRows(map);
    }
    function renderArtifacts() {
      const artifacts = filterItems(data.artifacts, ["artifact_id","artifact_path","artifact_type","source_file","description"]);
      const map = {};
      $("content").innerHTML = `<div class="card"><h3>Artifacts</h3><div class="list">${artifacts.map(a => {
        map["artifact:"+a.artifact_id]=a;
        return row(a.artifact_id, a.artifact_path || "", a, "artifact", a.artifact_id, `<span class="tag">${esc(a.artifact_type || "semantic")}</span><span class="tag">${esc(a.status || "")}</span>`);
      }).join("")}</div></div>`;
      bindRows(map);
    }
    function renderLenses() {
      const lenses = filterItems(data.lenses, ["lens_id","title","lens_type","content"]);
      const map = {};
      $("content").innerHTML = `<div class="card"><h3>Lenses</h3><div class="list">${lenses.map(l => {
        map["lens:"+l.lens_id]=l;
        return row(l.title || l.lens_id, (l.content || "").slice(0, 180), l, "lens", l.lens_id, `<span class="tag">${esc(l.lens_type)}</span>`);
      }).join("")}</div></div>`;
      bindRows(map);
    }
    function renderObjects() {
      const docs = filterItems(data.documents, ["rel_path","kind","title"]);
      const map = {};
      $("content").innerHTML = `<div class="card"><h3>Object Store</h3><div class="list">${docs.map(d => {
        map["document:"+d.document_id]=d;
        return row(d.rel_path, `${d.kind} · ${d.size_bytes} bytes · object=${d.object_path}`, d, "document", d.document_id, `<span class="tag">${esc(d.kind)}</span>`);
      }).join("")}</div></div>`;
      bindRows(map);
    }
    function render() {
      document.querySelectorAll("nav button[data-view]").forEach(b => b.classList.toggle("active", b.dataset.view === view));
      ({overview:renderOverview,navigation:renderNavigation,rounds:renderRounds,risks:renderRisks,cards:renderCards,artifacts:renderArtifacts,lenses:renderLenses,objects:renderObjects}[view] || renderOverview)();
    }
    $("headerSummary").innerHTML = `<span class="pill">${esc(data.summary.total_nodes)} nodes</span><span class="pill">${esc(data.summary.total_edges)} edges</span><span class="pill">latest: ${esc(data.summary.latest_artifact)}</span>`;
    document.querySelectorAll("nav button[data-view]").forEach(b => b.onclick = () => { view = b.dataset.view; render(); });
    $("search").oninput = () => render();
    $("saveDecision").onclick = () => {
      if (!selected) return;
      const key = "semanticReview:" + selected.type + ":" + selected.id;
      localStorage.setItem(key, JSON.stringify({decision:$("decision").value, notes:$("notes").value, updated_at:new Date().toISOString()}));
      alert("已保存本机审查状态");
    };
    render();
  </script>
</body>
</html>
"""


def write_dashboard(output_dir: Path, data: Dict[str, Any]) -> None:
    dashboard = output_dir / "dashboard"
    dashboard.mkdir(parents=True, exist_ok=True)
    (dashboard / "index.html").write_text(HTML, encoding="utf-8")
    js = "window.SEMANTIC_DASHBOARD_DATA = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"
    (dashboard / "dashboard_data.js").write_text(js, encoding="utf-8")
    (output_dir / "dashboard_data.json").write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def build(input_dir: Path, output_dir: Path) -> Dict[str, Any]:
    reset_output(output_dir)
    manifest = copy_objects(input_dir, output_dir)
    db_path = output_dir / "semantic_monitor.db"
    conn = connect_db(db_path)
    try:
        conn.executescript(SCHEMA)
        rel_to_doc = insert_documents(conn, input_dir, output_dir, manifest)
        insert_nodes_and_edges(conn, input_dir, rel_to_doc)
        insert_artifacts(conn, input_dir)
        insert_rounds(conn, input_dir)
        insert_markdown_derived(conn, input_dir, rel_to_doc)
        conn.commit()
        export_sql(conn, output_dir / "semantic_monitor.sql")
        data = build_dashboard_data(conn, input_dir)
    finally:
        conn.close()
    write_dashboard(output_dir, data)
    return {
        "db_path": str(db_path),
        "dashboard_path": str(output_dir / "dashboard" / "index.html"),
        "object_count": len(manifest),
        "output_dir": str(output_dir),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Build SQLite + local dashboard from semantic_monitor artifacts.")
    parser.add_argument("--input", required=True, help="Path to semantic_monitor directory")
    parser.add_argument("--output", required=True, help="Output directory for SQLite/object/dashboard bundle")
    args = parser.parse_args()
    input_dir = Path(args.input).resolve()
    output_dir = Path(args.output).resolve()
    if not input_dir.exists():
        raise SystemExit(f"input directory does not exist: {input_dir}")
    result = build(input_dir, output_dir)
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
